name: 0.0.1$(Rev:.r)_$(SourceBranchName)

trigger:
  batch: true
  branches:
    include:
      - master
  paths:
    include:
      - "Team-A/*"

pool:
  vmImage: "ubuntu-latest"

stages:
  - stage: DEV
    displayName: DEV
    jobs:
      - deployment: Deploy
        environment: "azure-kubernetes-service-dev-1"
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: self
                - template: ./templates/template.yml
                  parameters:
                    subscription: "Development Subscription"
                    aks_resource_group: "eu1-dev-aks-1-rg"
                    aks_name: "eu1-dev-aks-1"
                    namespace: "$(System.DefaultWorkingDirectory)/Team-A/cluster_config/namespace.yml"
                    service: "$(System.DefaultWorkingDirectory)/Team-A/cluster_config/service.yml"
                    SecretProviderClass: "$(System.DefaultWorkingDirectory)/Team-A/cluster_config/SecretProviderClass.yml"
                    aks_deployment: "$(System.DefaultWorkingDirectory)/Team-A/cluster_config/weather-eu-deploy.yml"
                    ingress: "$(System.DefaultWorkingDirectory)/Team-A/cluster_config/weather-eu-ingress.yml"
