apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: $kv-kv
  namespace: $namespace
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: $clientid
    keyvaultName: $kv
    objects: |
      array:
        - |
          objectName: $secret1
          objectType: secret
    tenantId: $tenantId
